spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:MDD-DUMP.sql
spring.sql.init.continue-on-error=true
spring.jpa.defer-datasource-initialization=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
logging.level.root=INFO
spring.jpa.show-sql=true
logging.level.com.openclassrooms.mddapi.exception=DEBUG
logging.file.name=logs/app.log
logging.com.example.demo=DEBUG
mdd.app.jwtsecret= 8t0vwAkYq/dwHkUOSOdl7jVnRNKcayRgJxIEDtNxvCb4Py4m72ye5oJoFQV4YWCy
mdd.app.expiretime= 864000000
server.port=3001
logging.level.org.springframework.boot.autoconfigure.h2=INFO
logging.level.org.springframework.boot.web.embedded.tomcat=INFO
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=UTC
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true